services:
  app:
    container_name: fxcustomimage
    image: fxcustomimage:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8532:8532"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    command: npm run dev
